export default [
  {
    place: "Шымбулак",
    title: "Ледник Богдановича",
    description: "Верхняя станция",
    elevation: 3200,
    src: "https://ipcam.kz/cam6/index.m3u8",
    poster: "/previews/3212b47c65ccc0cb9759f5c08632c563.jpg",
  },
  {
    place: "Шымбулак",
    title: "Средняя станция",
    description: "Средняя станция",
    elevation: 2800,
    src: "https://ipcam.kz/cam5/index.m3u8",
    poster: "/previews/ffa10e45b1d87ab0aa8796bc7969046c.jpg",
  },
  {
    place: "Шымбулак",
    title: "Подъемник",
    description: "Базовая станция",
    elevation: 2300,
    src: "https://ipcam.kz/cam1/index.m3u8",
    poster: "/previews/197f1dde9a2c929cca5496f225cc2d62.jpg",
  },
  {
    place: "Шымбулак",
    title: "Бугель",
    description: "Базовая станция",
    elevation: 2300,
    src: "https://ipcam.kz/cam2/index.m3u8",
    poster: "/previews/d5361ff25a96271df9ac614d9138806a.jpg",
  },
  {
    place: "Ой-Карагай",
    title: "Ride School",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=64805253ca75c",
    src: "https://s10.ipcamlive.com/streams/0afqidwhvmd2loxsx/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "Детский центр Ugusha",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=649512363558f",
    src: "https://s27.ipcamlive.com/streams/1bosxsg7qvwaeo6q3/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "Lift C",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=618a37bca3032",
    src: "",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "Aport Alatau",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=5eea13b9a2033",
    src: "https://s10.ipcamlive.com/streams/0ay9om1gxhw4pbmly/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "Lift A",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=5eea1409ae7c6",
    src: "https://s27.ipcamlive.com/streams/1bgiy1ph2wiqvucj6/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "Смотровая площадка ресторана 1820",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=5eea136cb1259",
    src: "https://s10.ipcamlive.com/streams/0au6gymwejnv3lbrx/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "Склон Irbis",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=6480555a49df5",
    src: "https://s46.ipcamlive.com/streams/2eerbrqmqg01szn4m/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "AQTAS Нижняя станция (Lift G)",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=67d2e7928082f",
    src: "https://s122.ipcamlive.com/streams/7abr5twfyoi67g8ez/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "AQTAS Верхняя станция (Lift G)",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=67d3bf2f1365e",
    src: "https://s122.ipcamlive.com/streams/7al7zhpxacr6nxpme/stream.m3u8",
    poster: "",
  },
  {
    place: "Ой-Карагай",
    title: "AQTAS Верхняя станция (Lift F)",
    description: "Курорт Ой-Карагай",
    player: "https://g2.ipcamlive.com/player/player.php?alias=6870f9f94a5f3",
    src: "https://s34.ipcamlive.com/streams/22g46srfitjoqmiy0/stream.m3u8",
    poster: "",
  },
];
